const filterRules = [
  {
    zones: ['RF-1', 'RF-2', 'RF-3', 'RF-4', 'RF-5'],
    sqft: 2645,
  },
  {
    zones: ['RA-1', 'RA-6'],
    sqft: 1763,
  },
  {
    zones: [
      'RA-2',
      'RA-3',
      'RA-4',
      'RA-5',
      'RA-7',
      'RA-8',
      'RA-9',
      'RA-10',
      'CG-1',
      'CG-2',
      'CG-3',
      'CG-4',
      'CG-5',
      'CG-6',
      'CG-7',
      'ARTS-1',
      'ARTS-2',
      'ARTS-3',
      'ARTS-4',
      'RC-1',
      'RC-2',
      'RC-3',
      'RC-4',
      'WR-1',
      'WR-2',
      'WR-3',
      'WR-4',
      'WR-5',
      'WR-6',
      'WR-7',
      'WR-8',
      'STE-1',
      'STE-2',
      'STE-3',
      'STE-4',
      'STE-5',
      'STE-6',
      'STE-7',
      'STE-8',
      'STE-9',
      'STE-10',
      'STE-11',
      'STE-12',
      'STE-13',
      'STE-14',
      'STE-15',
      'STE-16',
      'STE-17',
      'STE-18',
      'STE-19',
      'HE-1',
      'HE-2',
      'HE-3',
      'HE-4',
      'SEFC-1',
      'SEFC-2',
      'SEFC-3',
      'SEFC-4',
      'PDR-1',
      'PDR-2',
      'PDR-3',
      'PDR-4',
      'PDR-5',
      'PDR-6',
      'PDR-7',
      'USN',
    ],
    sqft: 400,
  },
  {
    zones: ['R-1-A', 'R-6', 'R-8', 'R-11', 'R-14'],
    sqft: 146999,
  },
  {
    zones: ['R-1-B', 'R-7', 'R-9', 'R-12', 'R-15', 'R-16', 'R-19'],
    sqft: 9799,
  },
  {
    zones: ['R-2', 'R-3', 'R-13', 'R-17', 'R-20'],
    sqft: 5879,
  },
  {
    zones: ['R-21'],
    sqft: 18620,
  },
];

module.exports.goodpropsFilter = (tasks) => {
  return tasks.filter((task) => {
    const rule = filterRules.find((r) => r.zones.includes(task.result.Zoning));
    if (!rule) return false;
    const sqft = Math.max(task.result['Tax Land Area'] || 0, task.result['Computed-Surveyed Area'] || 0, 0);
    return sqft >= rule.sqft;
  });
};
