module.exports = {
  '16th Street Heights': 'Tier I',
  'American University': 'Tier I',
  Anacostia: 'Tier III',
  'Barry Farms': 'Tier III',
  Berkeley: 'Tier I',
  Berkley: 'Tier I',
  Brentwood: 'Tier II',
  Brightwood: 'Tier II',
  Brookland: 'Tier II',
  'Capitol Hill': 'Tier I',
  Central: 'Tier I',
  'Chevy Chase': 'Tier I',
  Chillum: 'Tier II',
  'Cleveland Park': 'Tier I',
  'Colonial Village': 'Tier I',
  'Columbia Heights': 'Tier II',
  'Congress Heights': 'Tier III',
  Crestwood: 'Tier I',
  Deanwood: 'Tier III',
  Eckington: 'Tier II',
  'Foggy Bottom': 'Tier I',
  'Forest Hills': 'Tier I',
  'Fort Dupont Park': 'Tier III',
  'Fort Lincoln': 'Tier III',
  Foxhall: 'Tier I',
  Garfield: 'Tier I',
  Georgetown: 'Tier I',
  'Glover Park': 'Tier I',
  Hawthorne: 'Tier I',
  Hillcrest: 'Tier III',
  Kalorama: 'Tier I',
  Kent: 'Tier I',
  'Ledroit Park': 'Tier I',
  'Lily Ponds': 'Tier III',
  'Marshall Heights': 'Tier III',
  'Massachusetts Heights': 'Tier I',
  'Michigan Avenue': 'Tier II',
  'Michigan Park': 'Tier II',
  'Mount Pleasant': 'Tier I',
  'North Cleveland Park': 'Tier I',
  'Observatory Circle': 'Tier I',
  'Old City 1': 'Tier II',
  'Old City 2': 'Tier II',
  Palisades: 'Tier I',
  Petworth: 'Tier II',
  'R. L. A. NE': 'Tier II',
  'R. L. A. SW': 'Tier II',
  'Randle Heights': 'Tier III',
  'Riggs Park': 'Tier II',
  'Shepherd Park': 'Tier I',
  'Spring Valley': 'Tier I',
  Takoma: 'Tier II',
  'Takoma Park': 'Tier II',
  Trinidad: 'Tier II',
  Wakefield: 'Tier I',
  'Washington Navy Yard': 'Tier II',
  Wesley: 'Tier I',
  'Wesley Heights': 'Tier I',
  Woodley: 'Tier I',
  Woodridge: 'Tier II',
};
